USE[GD2015C1]
GO

/*
ENUNCIADO 6-7-22

REALIZAR UNA CONSULTA SQL QUE MUESTRE A AQUELLOS CLIENTES QUE NO COMPRAN PRODUCTOS COMPUESTOS
EN EL 2011 PERO SI EN EL 2012

*NUMERO DE FILA: SE CONSIDERA 1 AL CLIENTE QUE MENOS COMPRO Y N AL QUE MAS COMPRO
*MONTO TOTAL COMPRADO DEL CLIENTE EN EL 2012
*CANTIDAD DE RUBROS DISTINTOS COMPRADOS EN EL 2012
*/










-- ===================== T SQL ===========================

/*
IMPLEMENTAR EL O LOS OBJETOS NECESARIOS PARA QUE SIEMPRE SE CUMPLAN LAS SIGUIENTES 
REGLAS DE NEGOCIO

NUNCA EL PRECIO DE UN PRODUCTO COMPUESTO PUEDE SER DISTINTO A LA SUMA DE LOS PRECIOS
POR LAS CANTIDADES DE LOS PRODUCTOS QUE LO COMPONEN
*/